name: "Terraform Promotion v2 Dev -> Test -> Prod"

on: workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/plan_and_apply_template.yaml
    with:
      environments: dev
    secrets:
      inherit
